// Generates src/ui/assets.js: small binary assets as data: URIs.
//
// They are embedded rather than shipped as files because the deploy path
// depends on the plugin being a single file. `ensure_plugin` compares content,
// the uninstaller removes the folder, and in guest mode all of that happens
// inside a THIRD PARTY's directory -- more files there is more to get wrong in
// somebody else's product. Measured in the client: there is no CSP, so data:
// URIs are unconstrained.
//
// Fonts are deliberately NOT here. We render inside the client, which already
// has Riot's own faces loaded, and @font-face rules are document-global -- so
// they apply inside our shadow root for free. Bundling substitutes would cost
// ~124KB to look worse.
import { readFileSync, writeFileSync } from 'node:fs';

const assets = {
  DRAKE_ICON: ['assets/drake.png', 'image/png'],
  CHECKBOX_SPRITE: ['assets/checkbox-spritesheet.png', 'image/png'],
  // The client's own '#' glyph, so the Riot ID field matches theirs exactly.
  HASHTAG: ['assets/hashtag.svg', 'image/svg+xml'],
};

// The client serves no ranked emblem we can reach -- measured 400 on both
// /ranked-mini-crests/ and /ranked-emblems/ -- so these ship with the plugin.
// Eleven SVGs, ~20KB in total.
const RANK_TIERS = [
  'iron', 'bronze', 'silver', 'gold', 'platinum', 'emerald',
  'diamond', 'master', 'grandmaster', 'challenger', 'unranked',
];

let out = '// GENERATED by gen-assets.mjs -- do not edit by hand.\n\n';

for (const [name, [path, mime]] of Object.entries(assets)) {
  const b64 = readFileSync(path).toString('base64');
  out += `export const ${name} = 'data:${mime};base64,${b64}';\n\n`;
}

out += 'export const RANK_ICONS = {\n';
for (const tier of RANK_TIERS) {
  const b64 = readFileSync(`assets/rank/${tier}.svg`).toString('base64');
  out += `  ${tier.toUpperCase()}: 'data:image/svg+xml;base64,${b64}',\n`;
}
out += '};\n';

writeFileSync('src/ui/assets.js', out);
console.log('wrote src/ui/assets.js');
